on:
  push:
    branches:
      - master
jobs:
  action-test-job:
    runs-on: ubuntu-latest
    name: Deploying the application
    steps:
      - name: Create a change event
        uses: actions/pagerduty-change-events-action@master
        with:
          integration-key: 'c2334fd595f04d00c0ff7a204d8122d0'
